name: Trivy SCA

on:
  push:
    branches: [ "main" ]
    
jobs:
    Scan:
      uses: t-kolev/ric-plt-xapp-frame/.github/workflows/trivy.yml@master
      permissions:
        contents: read # for actions/checkout to fetch code
        security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
        actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      
